# Generated by Django 4.2.7 on 2023-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='testf',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='test_fil',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
