# Generated by Django 4.2.7 on 2023-12-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments_testf_post_test_fil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='testf',
        ),
        migrations.RemoveField(
            model_name='post',
            name='test_fil',
        ),
    ]
